services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai
    ports:
      - "5432:5432"
